# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nevis/amsterdam/share/seligman/conda/grams/bin/cmake

# The command to remove a file.
RM = /nevis/amsterdam/share/seligman/conda/grams/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /nevis/milne/files/ms6556/Flat/GramsSimSensitivity

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /nevis/milne/files/ms6556/Flat/GramsSimSensitivity

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/nevis/amsterdam/share/seligman/conda/grams/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/nevis/amsterdam/share/seligman/conda/grams/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /nevis/milne/files/ms6556/Flat/GramsSimSensitivity/CMakeFiles /nevis/milne/files/ms6556/Flat/GramsSimSensitivity//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /nevis/milne/files/ms6556/Flat/GramsSimSensitivity/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GramsSensitivitySenseUtilities

# Build rule for target.
GramsSensitivitySenseUtilities: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GramsSensitivitySenseUtilities
.PHONY : GramsSensitivitySenseUtilities

# fast build rule for target.
GramsSensitivitySenseUtilities/fast:
	$(MAKE) $(MAKESILENT) -f SensitivityUtils/CMakeFiles/GramsSensitivitySenseUtilities.dir/build.make SensitivityUtils/CMakeFiles/GramsSensitivitySenseUtilities.dir/build
.PHONY : GramsSensitivitySenseUtilities/fast

#=============================================================================
# Target rules for targets named GramsSensitivityExtract

# Build rule for target.
GramsSensitivityExtract: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GramsSensitivityExtract
.PHONY : GramsSensitivityExtract

# fast build rule for target.
GramsSensitivityExtract/fast:
	$(MAKE) $(MAKESILENT) -f SensitivityUtils/CMakeFiles/GramsSensitivityExtract.dir/build.make SensitivityUtils/CMakeFiles/GramsSensitivityExtract.dir/build
.PHONY : GramsSensitivityExtract/fast

#=============================================================================
# Target rules for targets named GramsSensitivityReadRoot

# Build rule for target.
GramsSensitivityReadRoot: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GramsSensitivityReadRoot
.PHONY : GramsSensitivityReadRoot

# fast build rule for target.
GramsSensitivityReadRoot/fast:
	$(MAKE) $(MAKESILENT) -f SensitivityUtils/CMakeFiles/GramsSensitivityReadRoot.dir/build.make SensitivityUtils/CMakeFiles/GramsSensitivityReadRoot.dir/build
.PHONY : GramsSensitivityReadRoot/fast

#=============================================================================
# Target rules for targets named GramsSensitivityReconstructUtils

# Build rule for target.
GramsSensitivityReconstructUtils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GramsSensitivityReconstructUtils
.PHONY : GramsSensitivityReconstructUtils

# fast build rule for target.
GramsSensitivityReconstructUtils/fast:
	$(MAKE) $(MAKESILENT) -f SensitivityUtils/CMakeFiles/GramsSensitivityReconstructUtils.dir/build.make SensitivityUtils/CMakeFiles/GramsSensitivityReconstructUtils.dir/build
.PHONY : GramsSensitivityReconstructUtils/fast

#=============================================================================
# Target rules for targets named GramsSensitivityGenSkyMapUtils

# Build rule for target.
GramsSensitivityGenSkyMapUtils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GramsSensitivityGenSkyMapUtils
.PHONY : GramsSensitivityGenSkyMapUtils

# fast build rule for target.
GramsSensitivityGenSkyMapUtils/fast:
	$(MAKE) $(MAKESILENT) -f SensitivityUtils/CMakeFiles/GramsSensitivityGenSkyMapUtils.dir/build.make SensitivityUtils/CMakeFiles/GramsSensitivityGenSkyMapUtils.dir/build
.PHONY : GramsSensitivityGenSkyMapUtils/fast

#=============================================================================
# Target rules for targets named GramsSensitivityCalcSenseUtils

# Build rule for target.
GramsSensitivityCalcSenseUtils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GramsSensitivityCalcSenseUtils
.PHONY : GramsSensitivityCalcSenseUtils

# fast build rule for target.
GramsSensitivityCalcSenseUtils/fast:
	$(MAKE) $(MAKESILENT) -f SensitivityUtils/CMakeFiles/GramsSensitivityCalcSenseUtils.dir/build.make SensitivityUtils/CMakeFiles/GramsSensitivityCalcSenseUtils.dir/build
.PHONY : GramsSensitivityCalcSenseUtils/fast

#=============================================================================
# Target rules for targets named Extract

# Build rule for target.
Extract: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Extract
.PHONY : Extract

# fast build rule for target.
Extract/fast:
	$(MAKE) $(MAKESILENT) -f SensitivityUtils/Extraction/CMakeFiles/Extract.dir/build.make SensitivityUtils/Extraction/CMakeFiles/Extract.dir/build
.PHONY : Extract/fast

#=============================================================================
# Target rules for targets named Reconstruct

# Build rule for target.
Reconstruct: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Reconstruct
.PHONY : Reconstruct

# fast build rule for target.
Reconstruct/fast:
	$(MAKE) $(MAKESILENT) -f SensitivityUtils/Reconstruction/CMakeFiles/Reconstruct.dir/build.make SensitivityUtils/Reconstruction/CMakeFiles/Reconstruct.dir/build
.PHONY : Reconstruct/fast

#=============================================================================
# Target rules for targets named GenSkyMap

# Build rule for target.
GenSkyMap: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GenSkyMap
.PHONY : GenSkyMap

# fast build rule for target.
GenSkyMap/fast:
	$(MAKE) $(MAKESILENT) -f SensitivityUtils/GenSkyMap/CMakeFiles/GenSkyMap.dir/build.make SensitivityUtils/GenSkyMap/CMakeFiles/GenSkyMap.dir/build
.PHONY : GenSkyMap/fast

#=============================================================================
# Target rules for targets named CalcSensi

# Build rule for target.
CalcSensi: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 CalcSensi
.PHONY : CalcSensi

# fast build rule for target.
CalcSensi/fast:
	$(MAKE) $(MAKESILENT) -f Source/CMakeFiles/CalcSensi.dir/build.make Source/CMakeFiles/CalcSensi.dir/build
.PHONY : CalcSensi/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... CalcSensi"
	@echo "... Extract"
	@echo "... GenSkyMap"
	@echo "... GramsSensitivityCalcSenseUtils"
	@echo "... GramsSensitivityExtract"
	@echo "... GramsSensitivityGenSkyMapUtils"
	@echo "... GramsSensitivityReadRoot"
	@echo "... GramsSensitivityReconstructUtils"
	@echo "... GramsSensitivitySenseUtilities"
	@echo "... Reconstruct"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

